services:
  tadashi:
    user: ${UID}:${GID}
    build:
      dockerfile: ./tadashi.dockerfile
      args:
        - USER=${USER}
        - UID=${UID}
        - GROUP=${GROUP}
        - GID=${GID}
    # env_file:
    #   .env
    volumes:
      - ..:/workdir
    environment:
      - PKG_CONFIG_PATH=/tadashi/build/_deps/libpet-src:/tadashi/build/_deps/libpet-src/isl
      - LIBRARY_PATH=/tadashi/build/_deps/libpet-build/lib
