name: Run tests
on: push

jobs:
  build-pet:
    name: Build PET
    runs-on: ubuntu-latest
    steps:

    - name: Install packages 📦
      run: >
        sudo apt-get install -y
        git build-essential autoconf pkg-config libtool libc++-dev
        libyaml-dev libntl-dev libgmp-dev llvm clang llvm-dev
        libclang-dev python-is-python3

    - name: Set up Python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        # cache: 'pip'

    - name: Check out repo
      uses: actions/checkout@master

    - name: Configure Project
      # continue-on-error: true
      uses: threeal/cmake-action@v1.3.0
      with:
        generator: Ninja

    - name: Build Project
      run: cmake --build build

    - name: Run cmake gtest
      run: ctest --test-dir build

    - name: Run random_rl.py
      run: python -m tadashi

    - name: Run simple.py
      run: python -m tadashi.simple

    - name: Run unittests
      run: python -m unittest
